### ISSUE TITLE
ACF compatibility fatal error 

### ISSUE THREAD

**Issue by akshaywali** [ahmedkaludi/Easy-Table-of-Contents#526]
Warning: Array to string conversion in /home/dengemch/public_html/preview.dengem.ch/wp-content/plugins/easy-table-of-contents-pro/compatibility.php on line 73

Fatal error: Uncaught TypeError: mb_strpos(): Argument #1 ($haystack) must be of type string, array given in /home/dengemch/public_html/preview.dengem.ch/wp-content/plugins/easy-table-of-contents/includes/inc.cord-functions.php:300 Stack trace: #0 /home/dengemch/public_html/preview.dengem.ch/wp-content/plugins/easy-table-of-contents/includes/inc.cord-functions.php(300): mb_strpos(Array, '>What is Lorem ...') #1 /home/dengemch/public_html/preview.dengem.ch/wp-content/plugins/easy-table-of-contents-pro/compatibility.php(27): Easy_Plugins\Table_Of_Contents\Cord\mb_find_replace(Array, Array, Array) #2 /home/dengemch/public_html/preview.dengem.ch/wp-includes/class-wp-hook.php(310): eztoc_pro_acf_load_value(Array) #3 /home/dengemch/public_html/preview.dengem.ch/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array) #4 /home/dengemch/public_html/preview.dengem.ch/wp-content/plugins/advanced-custom-fields-pro/includes/acf-value-functions.php(118): apply_filters('acf/load_value', '', 1840, Array) #5 /home/dengemch/public_html/preview.dengem.ch/wp-content/plugins/advanced-custom-fields-pro/includes/api/api-template.php(45): acf_get_value(1840, Array) #6 /home/dengemch/public_html/preview.dengem.ch/wp-content/themes/dengem/header.php(65): get_field('main--image__gr...') #7 /home/dengemch/public_html/preview.dengem.ch/wp-includes/template.php(783): require_once('/home/dengemch/...') #8 /home/dengemch/public_html/preview.dengem.ch/wp-includes/template.php(718): load_template('/home/dengemch/...', true, Array) #9 /home/dengemch/public_html/preview.dengem.ch/wp-includes/general-template.php(48): locate_template(Array, true, true, Array) #10 /home/dengemch/public_html/preview.dengem.ch/wp-content/themes/dengem/single.php(11): get_header() #11 /home/dengemch/public_html/preview.dengem.ch/wp-includes/template-loader.php(106): include('/home/dengemch/...') #12 /home/dengemch/public_html/preview.dengem.ch/wp-blog-header.php(19): require_once('/home/dengemch/...') #13 /home/dengemch/public_html/preview.dengem.ch/index.php(17): require('/home/dengemch/...') #14 {main} thrown in /home/dengemch/public_html/preview.dengem.ch/wp-content/plugins/easy-table-of-contents/includes/inc.cord-functions.php on line 300

**Comment by akshaywali** [comment]
https://github.com/ahmedkaludi/easy-table-of-contents-pro/commit/34680b5d2e5c897009b975bcd5ed56bd3b16100c
